### ISSUE TITLE
hook release filename changed

### ISSUE THREAD

**Issue by jmpolom** [tinkerbell/hook#75]
## Expected Behaviour
  1. The default sandbox configuration should work with hook, since it is set as default.
  2. Release assets should not be updated/replaced without a new release being made. It is extremely confusing when release assets change and the date is not updated to reflect that there was indeed a recent change.

## Current Behaviour
Sandbox will not be able to pull hook since it references `OSIE_DOWNLOAD_URL="https://github.com/tinkerbell/hook/releases/download/5.10.57/hook-x86_64.tar.gz"` and that file no longer exists. The x86_64 release for hook now lives at `https://github.com/tinkerbell/hook/releases/download/5.10.57/hook_x86_64.tar.gz`. This name change also seems to break the `osie/lastmile.sh` script in sandbox since filenames have changed inside the hook release archive.

We may have also experienced additional issues with the latest hook asset available on the release page. It seemed like hook wasn't properly trusting or able to connect to the sandbox registry after we made some modifications to work with the current version of hook available on the release page.

## Possible Solution
Keeping consistent with filenames for hook would be very beneficial if other things depend on that naming. Additionally, some documentation for general hook configuration and troubleshooting would be helpful.

## Steps to Reproduce (for bugs)

1. Examine `deploy/compose/.env` in sandbox
2. Compare default OSIE URL in `.env` against URL for current hook release

## Context
We are attempting to develop an ansible role to deploy the tinkerbell sandbox and this issue has perplexed us quite a bit. It is our opinion that release artifacts should not change without also some separate verbose acknowledgement that there's been a change to the release.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS): Fedora 34 and Debian

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details: Custom ansible.

* Link to your project or a code example to reproduce issue: https://github.com/jkl92/sandbox/tree/ansible-podman_container

**Comment by tstromberg** [comment]
@thebsdbox - any chance this issue is on your radar?

**Comment by jmpolom** [comment]
@tstromberg do you have any pointers on why hook would seem to be unable to contact the sandbox registry? We're pretty much following the same patterns in the sandbox docker-compose but deploying with ansible instead. We were kind of stumped when it came to debugging how hook determines:
- where the registry is located
- how to trust the registry
- how hook is made aware of any crypto keys that are necessary to trust or communicate with the registry

Does hook or the container payloads it runs ever communicate directly with the tink server? I couldn't really find any documentation about this aspect. If hook or payloads talk to the tink server it is also possible there was an issue with hook communicating with the workflow/tink server.

**Comment by jacobweinstock** [comment]
Hey @jmpolom, I'll try and answer these.

_- where the registry is located_

Hook has a built-in app ([bootkit](https://github.com/tinkerbell/hook/blob/main/bootkit/)) that runs at Hook startup which will parse kernel command line args. These cmdline args will be used when bootkit starts the tink-worker.
The parsing of the cmdline file happens [here](https://github.com/tinkerbell/hook/blob/cc08a3f4fd8014f442841a1ba6bd838eca4d2b0d/bootkit/main.go#L153) in bootkit.
For the container registry, bootkit is looking in the cmdline file for `docker_registry=` to determine where to pull images.

_- how to trust the registry_

To enable pulling images from an insecure container registry, [tink-docker](https://github.com/tinkerbell/hook/blob/main/tink-docker/main.go) downloads the container registry's public TLS cert and putting it in the local certificate trust store.
It gets the URL for this file via the cmdline file using the `packet_base_url=` value and appending `ca.pem`. So from the example cmdline below the TLS cert would be downloaded from `http://192.168.50.4:42114/cert/ca.pem`. 

_- how hook is made aware of any crypto keys that are necessary to trust or communicate with the registry_

The previous response answers how the insecure registry is trusted in Hook. The last part is that the container registry uses username/password for authentication. You'll see below in the cmdline examples that these creds are passed along to Hook via `registry_username` and `registry_password`. Bootkit parse them from the cmdline file and uses them to login when downloading the tink-worker. See [here](https://github.com/tinkerbell/hook/blob/cc08a3f4fd8014f442841a1ba6bd838eca4d2b0d/bootkit/main.go#L100). These creds are also passed into the Tink worker (see [here](https://github.com/tinkerbell/hook/blob/cc08a3f4fd8014f442841a1ba6bd838eca4d2b0d/bootkit/main.go#L71)) when it's started up so that it can pull images when running workflow.

_- Does hook or the container payloads it runs ever communicate directly with the tink server?_

Tink worker communicates with tink server. I don't believe Hook ever does. 

One final note. I've just put in a PR (https://github.com/tinkerbell/sandbox/pull/102) to get the sandbox back up and running with this new release of Hook. 

---

Example `/proc/cmdline`
```bash
ip=dhcp modules=loop,squashfs,sd-mod,usb-storage alpine_repo=http://192.168.50.4:8080/misc/osie/current/repo-x86_64/main modloop=http://192.168.50.4:8080/misc/osie/current/modloop-x86_64 tinkerbell=http://192.168.50.4 syslog_host=192.168.50.4 parch=x86_64 packet_action=workflow packet_state=provisioning docker_registry=192.168.50.4 grpc_authority=192.168.50.4:42113 grpc_cert_url=http://192.168.50.4:42114/cert instance_id= registry_username=admin registry_password=Admin1234 packet_base_url=http://192.168.50.4:8080/workflow worker_id=0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 packet_bootdev_mac=08:00:27:9e:f5:3a facility=onprem plan=c2.medium.x86 manufacturer= slug= initrd=initramfs-x86_64 console=tty0 console=ttyS1,115200
``` 
user-friendly format
```ini
ip=dhcp
modules=loop,squashfs,sd-mod,usb-storage
alpine_repo=http://192.168.50.4:8080/misc/osie/current/repo-x86_64/main
modloop=http://192.168.50.4:8080/misc/osie/current/modloop-x86_64
tinkerbell=http://192.168.50.4
syslog_host=192.168.50.4
parch=x86_64
packet_action=workflow
packet_state=provisioning
docker_registry=192.168.50.4
grpc_authority=192.168.50.4:42113
grpc_cert_url=http://192.168.50.4:42114/cert
instance_id=
registry_username=admin
registry_password=Admin1234
packet_base_url=http://192.168.50.4:8080/workflow
worker_id=0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94
packet_bootdev_mac=08:00:27:9e:f5:3a
facility=onprem
plan=c2.medium.x86
manufacturer=
slug=
initrd=initramfs-x86_64
console=tty0
console=ttyS1,115200
```

**Comment by jmpolom** [comment]
@jacobweinstock thanks for the quick response on a Friday before a holiday weekend in the US. Very helpful info for sure.d

> For the container registry, bootkit is looking in the cmdline file for docker_registry= to determine where to pull images.

Where is this set? I don't see it being set as an env var in the sandbox compose file. I'm guessing there are some defaults that are used (perhaps inferred from `$TINKERBELL_HOST_IP`?) but unsure where/how they are communicated to the host booting via iPXE. I'd imagine this happens somewhere within boots and is put into the dynamically generated `auto.pxe` iPXE script.

Definitely see how `/proc/cmdline` is being read there but I think our stumbling point is further up the chain. I'll test the changes you committed but we'd certainly like to understand how things are _supposed_ to work here. I've been kind of mindlessly poking around the boots codebase and haven't yet pinpointed where/how boots is creating the iPXE script that hook (or OSIE) get booted with.

**Comment by jacobweinstock** [comment]
Yeah, sorry. This is an area that is sorely missing documentation. Hopefully, this helps explain a little.

You are correct, _"within boots and is put into the dynamically generated auto.pxe iPXE script"_. This happens in this function [here](https://github.com/tinkerbell/boots/blob/ba3a3fef424ebfd7125b08ae99dcb9631bc911a8/installers/osie/main.go#L70) in Boots, and [here](https://github.com/tinkerbell/boots/blob/ba3a3fef424ebfd7125b08ae99dcb9631bc911a8/installers/osie/main.go#L98) and [here](https://github.com/tinkerbell/boots/blob/90f15b7c0924aef72211df8e7a38295a29ae7177/installers/osie/mirror.go#L55).
This docker registry is set via environment variable in Boots. You can see this in the sandbox, [here](https://github.com/tinkerbell/sandbox/blob/f10a1f085326c5691a149e356df5d35238bb62d4/deploy/compose/docker-compose.yml#L252).

**Comment by jmpolom** [comment]
I was just traversing those same sources about the time you posted your comment. I guess I'm not as clueless dumb as I thought. Between the new knowledge from your explanations and updated sandbox we probably have enough to at least be dangerous.

Documentation would certainly be helpful here but luckily go isn't too hard to read through.

**Comment by tstromberg** [comment]
https://github.com/tinkerbell/sandbox/pull/102 was merged which should address the primary issue here. I suggest that any outstanding ideas/issues be moved into their own issues for separate tracking.

**Comment by tstromberg** [comment]
Moved the release automation work to #78

/cc @thebsdbox
